name: 'Operate Actions CI'
description: 'Operate Actions CI'
author: 'yong'
inputs:
  repo_owner:
    description: 'The owner of the repository.'
    required: true
  repo_name:
    description: 'The name of the repository.'
    required: true
  rerun_cmd:
    description: 'The commands string to rerun all checks.'
    required: false
    default: 'run failure checks'
runs:
  using: 'node12'
  main: 'dist/index.js'
